seed_everything: 123

trainer:
  devices: 1
  accumulate_grad_batches: 5
  accelerator: gpu
  precision: bf16-mixed
  strategy: "ddp"
  use_distributed_sampler: False
  max_epochs: 100
  gradient_clip_val: 1.0

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        dirpath: checkpoints/${trainer.logger.init_args.experiment}
        filename: checkpoint_{epoch}_{step}_{val_loss:.4f}
        save_top_k: 3
        save_last: true
  logger:
   class_path: aim.pytorch_lightning.AimLogger
   init_args:
     experiment: lina_librilight-medium #_gla

data:
  class_path: dataset.ManifestDataModule
  init_args:
    root_path: "feats_medium_cut_25"
    train_manifest_path: "librilight_cutbyvad25s_manifest_length_v2.json"
    env_root: "DBROOT"
    quant_layer: [0, 1, 2, 3]
    batch_size: 16
    bucket_by_quantile: 10
    filter_min: 300
    filter_max: 2000
    symbols_file: "symbols.txt"
    phon_col: ".ocotillo.phonemized.txt"

model:
  class_path: model.lina.Lina
  init_args:
    n_codebook: 1024
    n_special_token_in: 3
    n_special_token_out: 3
    n_txt_vocab: 180
    d_context: 640
    d_model: 640
      #attentive_rnn:
      #  class_path: ttc.gla.AttentiveGLA
      #  init_args:
      #    d_model: ${model.init_args.d_model}
      #    d_context: ${model.init_args.d_context}
      #    att_heads: 1
      #    gla_heads: 1
      #    dropout_att: 0.1
      #    n_layer: 3
    txt_encoder:
      class_path: model.encoder.TextEncoder
      init_args:
        dim: ${model.init_args.d_context}
        heads: 1
        n_layers: 9
        dropout: 0.1
    attentive_rnn:
      class_path: model.mamba.AttentiveMamba
      init_args:
        d_model: ${model.init_args.d_model}
        d_context: ${model.init_args.d_context}
        heads: 1
        dropout_att: 0.1
        n_layer: 12
        blind: True
