seed_everything: 123

trainer:
  devices: 1
  accumulate_grad_batches: 2
  accelerator: gpu
  precision: bf16-mixed
  strategy: "ddp"
  max_epochs: 100
  use_distributed_sampler: False
  gradient_clip_val: 1.0

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        dirpath: checkpoints/${trainer.logger.init_args.name}
        filename: checkpoint_{epoch}_{step}_{val_loss:.4f}
        save_top_k: 3
        save_last: true


  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: logs
      name: ttc_libritts360clean #_gla

data:
  class_path: dataset.ManifestDataModule
  init_args:
    root_path: "LibriTTS/feats_train-clean-360"
    train_manifest_path: "simplettsdataset/libritts_train-clean-360_ttc_length.json"
    env_root: "DBROOT"
    quant_layer: [0, 1, 2, 3]
    batch_size: 26
    bucket_by_quantile: 5
    symbols_file: "symbols.txt"

model:
  class_path: model.lina.Lina
  init_args:
    n_codebook: 1024
    n_special_token_in: 3
    n_special_token_out: 3
    n_txt_vocab: 180
    d_context: 384
    d_model: 512
      #attentive_rnn:
      #  class_path: ttc.gla.AttentiveGLA
      #  init_args:
      #    d_model: ${model.init_args.d_model}
      #    d_context: ${model.init_args.d_context}
      #    att_heads: 1
      #    gla_heads: 1
      #    dropout_att: 0.1
      #    n_layer: 3
    txt_encoder:
      class_path: model.encoder.TextEncoder
      init_args:
        dim: ${model.init_args.d_context}
        heads: 1
        n_layers: 6
        dropout: 0.1
    attentive_rnn:
      class_path: model.gla.AttentiveGLA
      init_args:
        d_model: ${model.init_args.d_model}
        d_context: ${model.init_args.d_context}
        heads: 4
        dropout_att: 0.1
        n_layer: 3
        blind: True
