seed_everything: 123

trainer:
  devices: 2
  accumulate_grad_batches: 4
  accelerator: gpu
  precision: 16-mixed
  max_epochs: 100

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        dirpath: ttc/checkpoints/${trainer.logger.init_args.name}
        filename: checkpoint_{epoch}_{step}_{val_loss:.4f}
        save_top_k: 3
        save_last: true

  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: ttc/logs
      name: ttc_libritts

data:
  class_path: ttc.dataset.ManifestDataModule
  init_args:
    dataset: 
      class_path: ttc.dataset.ManifestRWKVDataset
      init_args:
        root_path: "LibriTTS/feats_train-other-500"
        manifest_path: "LibriTTS/feats_manifest_rwkv_filter_v2.json"
        env_root: "DBROOT"
        symbols_file: "symbol.txt"
        quant_layer: [0, 1]
          
    batch_size: 12

model:
  class_path: ttc.ttc.TTC
  init_args:
    n_quant: 2
    n_codebook: 1024
    n_special_token_in: 3
    n_special_token_out: 3
    n_txt_vocab: 180
    context_dim: 256
    text_encoder:
      class_path: ttc.encoder.TextEncoderV2
      init_args:
        dim: 256
        heads: 4
        n_layers: 6
        dropout: 0.1
    rwkv_config:
      block_size: 1008
      n_layer: 8
      n_embd: 640
      dropout: 0.1
      heads: 2
      attentive_layer: [1,2]
      dropout_att: 0.1
      context_dim: ${model.init_args.context_dim}
        
