seed_everything: 123

trainer:
  accelerator: gpu
  precision: bf16-mixed
  strategy: "ddp"
  devices: 2
  max_epochs: 100
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: lina
      name: lina_gla_230_librilight


  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        dirpath: ttc/checkpoints/${trainer.logger.init_args.name}
        filename: checkpoint_{epoch}_{step}_{val_loss:.4f}
        save_top_k: 1
        save_last: true
  
  
  # logger:
  #   class_path: pytorch_lightning.loggers.TensorBoardLogger
  #   init_args:
  #     save_dir: logs
  #     name: lina_ljspeech #_gla

data:
  class_path: dataset.LinaDataModule
  init_args:
    path: "theodorr/librilight_medium"
    quant_layer: [0, 1, 2, 4]

model:
  class_path: model.lina.Lina
  init_args:
    n_warmup_steps: 500
    n_training_steps: 500000
    n_codebook: 1024
    n_special_token_in: 3
    n_special_token_out: 3
    n_txt_vocab: 256
    d_context: 1024
    d_model: 1024
    txt_encoder:
      class_path: model.encoder.TextEncoder
      init_args:
        dim: ${model.init_args.d_context}
        heads: 4
        n_layers: 9
        dropout: 0.1
    attentive_rnn:
      class_path: model.gla.AttentiveGLA
      init_args:
        d_model: ${model.init_args.d_model}
        d_context: ${model.init_args.d_context}
        dropout_att: 0.1
        dropout: 0.
        heads: 4
        n_layer: 6
        blind: True
        d_blind: 512
